application:
  name: sample-swinch-chart
  email: example@example.com

global:
  bake:
    inputArtifacts:
      account: stable
      name: redis
      version: 10.5.7

# Note the list of pipelines
complex_pipelines:
  enabled: true
  pipelines:
    - name: complexParallelPipe1
      stages:
        bake:
          - name: "Bake 1"
            namespace: swinch
        deploy:
          - name: "Deploy 1"
            cluster: MyCluster1
            namespace: swinch
            account: test
        delete:
          - name: "Delete 1"
            namespace: swinch
            account: test
    - name: complexParallelPipe2
      stages:
        bake:
          - name: "Bake 1"
            namespace: swinch
          - name: "Bake 2"
            namespace: swinch
        deploy:
          - name: "Deploy 1"
            cluster: MyCluster1
            namespace: swinch
            account: test
          - name: "Deploy 2"
            cluster: MyCluster2
            namespace: swinch
            account: test
        delete:
          - name: "Delete"
            namespace: swinch
            account: test
