application:
  name: sample-swinch-chart
  email: dcoman@adobe.com
  ldap: "ee_spinnaker_all"

global:
  bake:
    inputArtifacts:
      account: stable
      name: redis
      version: 10.5.7


parallel_pipeline:
  enabled: true
  name: parallelPipes
  stages:
    bake:
      - name: "Bake 1"
        namespace: swinch
      - name: "Bake 2"
        namespace: swinch
    deploy:
      - name: "Deploy 1"
        cluster: MyCluster1
        namespace: swinch
        account: test
      - name: "Deploy 2"
        cluster: MyCluster2
        namespace: swinch
        account: test
    delete:
      - name: "Delete 1"
        namespace: swinch
        account: test

# Note stages.bake and stages.delete are not lists
# deploy stages ar mapped to the single bake stage with bakeStageRefIds key
serial_pipeline:
  enabled: true
  name: simplePipe
  stages:
    bake:
      name: "Bake 1"
      namespace: swinch
    deploy:
      - name: "Deploy 1"
        cluster: MyCluster1
        namespace: swinch
        account: test
      - name: "Deploy 2"
        cluster: MyCluster2
        namespace: swinch
        account: test
    manual_judgment:
      enabled: true
      name: "Manual Judgment before Delete"
      stageTimeoutMs: 1800000
    delete:
      name: "Delete 1"
      namespace: swinch
      account: test

# Note the list of pipelines
complex_pipelines:
  enabled: true
  pipelines:
    - name: complexParallelPipe1
      stages:
        bake:
          - name: "Bake 1"
            namespace: swinch
        deploy:
          - name: "Deploy 1"
            cluster: MyCluster1
            namespace: swinch
            account: test
        delete:
          - name: "Delete 1"
            namespace: swinch
            account: test
    - name: complexParallelPipe2
      stages:
        bake:
          - name: "Bake 1"
            namespace: swinch
          - name: "Bake 2"
            namespace: swinch
        deploy:
          - name: "Deploy 1"
            cluster: MyCluster1
            namespace: swinch
            account: test
          - name: "Deploy 2"
            cluster: MyCluster2
            namespace: swinch
            account: test
        delete:
          - name: "Delete"
            namespace: swinch
            account: test
