{{- if .Values.parallel_pipeline -}}
  {{- $application := .Values.application.name -}}
  {{- $global := .Values.global -}}
  {{- $pipeline := .Values.parallel_pipeline -}}
  {{- $lenBake := len $pipeline.stages.bake -}}
  {{- $lenDeploy := len $pipeline.stages.deploy -}}
---
apiVersion: spinnaker.adobe.com/alpha1
kind: Pipeline
metadata:
  name: {{ $pipeline.name }}
  application: {{ $application }}
spec:
# TODO auto index all pipelines in an application
  index: 3
  keepWaitingPipelines: false
  limitConcurrent: true
  spelEvaluator: v4
  stages:
    # Presume 1:1 bake to deploy stage ratio
    {{- range $bake_index, $bake := $pipeline.stages.bake }}
    - name: "{{ $bake.name }}"
      type: bakeManifest
      namespace: "{{ $bake.namespace }}"
      outputName: redis
      requisiteStageRefIds: []
      templateRenderer: HELM2
      inputArtifacts:
        - account: {{ $global.bake.inputArtifacts.account }}
          artifact:
            name: {{ $global.bake.inputArtifacts.name }}
            type: helm/chart
            version: {{ $global.bake.inputArtifacts.version }}
      expectedArtifacts:
        - displayName: redis
          matchArtifact:
            artifactAccount: embedded-artifact
            name: redis
            type: embedded/base64
    {{ end }}
    {{- range $deploy_index, $deploy := $pipeline.stages.deploy }}
    - name: "{{ $deploy.name }} in {{ $deploy.cluster }} from {{$pipeline.name}}"
      # We loop over the deploy stages, but as we presume a 1:1 ratio to bake we can use the deploy index to refer back
      # to the bake index
      # Add one to the index, go template starts from 0, spinnaker starts from 1
      requisiteStageRefIds:
        - {{  add $deploy_index 1 }}
      type: deployManifest
      account: "{{ $deploy.account }}"
      cloudProvider: kubernetes
      namespaceOverride: "{{ $deploy.namespace }}"
      skipExpressionEvaluation: true
      source: artifact
    {{ end }}
    {{- range $index, $delete := $pipeline.stages.delete }}
    - name: Delete (Manifest)
      requisiteStageRefIds:
      {{- range $index, $value := $pipeline.stages.deploy }}
      - {{ add 1 $index $lenBake -}}
      {{ end }}
      type: deleteManifest
      account:  "{{ $delete.account }}"
      cloudProvider: kubernetes
      kinds:
        - statefulSet
        - configMap
        - secret
        - persistentVolumeClaim
        - service
      labelSelectors:
        selectors:
          - key: app
            kind: EQUALS
            values:
              - redis
      namespace: "{{ $delete.namespace }}"
      mode: label
      options:
        cascading: true
  triggers: []
    {{ end }}
{{ end }}

