{{- if .Values.serial_pipeline.enabled -}}
  {{- $application := .Values.application.name -}}
  {{- $global := .Values.global -}}
  {{- $pipeline := .Values.serial_pipeline -}}
  {{- $lenBake := 1 -}}
  {{- $lenDeploy := len $pipeline.stages.deploy -}}
---
apiVersion: spinnaker.adobe.com/alpha1
kind: Pipeline
metadata:
  name: {{ $pipeline.name }}
  application: {{ $application }}
spec:
# TODO auto index all pipelines in an application
  index: 1
  keepWaitingPipelines: false
  limitConcurrent: true
  spelEvaluator: v4
  stages:
    {{- $bake := $pipeline.stages.bake }}
    - name: "{{ $bake.name }}"
      type: bakeManifest
      namespace: "{{ $bake.namespace }}"
      outputName: redis
      requisiteStageRefIds: []
      templateRenderer: HELM2
      inputArtifacts:
        - account: {{ $global.bake.inputArtifacts.account }}
          artifact:
            name: {{ $global.bake.inputArtifacts.name }}
            type: helm/chart
            version: {{ $global.bake.inputArtifacts.version }}
      expectedArtifacts:
        - displayName: redis
          matchArtifact:
            artifactAccount: embedded-artifact
            name: redis
            type: embedded/base64
    {{- range $deploy_index, $deploy := $pipeline.stages.deploy }}
    - name: "{{ $deploy.name }} in {{ $deploy.cluster }} from {{$pipeline.name}}"
      # Extra field to bind the manifestArtifactId of every deploy stage to a single build stage
      bakeStageRefIds: 1
      requisiteStageRefIds:
        - {{  add $deploy_index $lenBake }}
      type: deployManifest
      account: "{{ $deploy.account }}"
      cloudProvider: kubernetes
      namespaceOverride: "{{ $deploy.namespace }}"
      skipExpressionEvaluation: true
      source: artifact
    {{ end }}
    {{- $delete := $pipeline.stages.delete }}
    - name: Delete (Manifest)
      requisiteStageRefIds:
      - {{ add $lenBake $lenDeploy }}
      type: deleteManifest
      account:  "{{ $delete.account }}"
      cloudProvider: kubernetes
      kinds:
        - statefulSet
        - configMap
        - secret
        - persistentVolumeClaim
        - service
      labelSelectors:
        selectors:
          - key: app
            kind: EQUALS
            values:
              - redis
      namespace: "{{ $delete.namespace }}"
      mode: label
      options:
        cascading: true
  triggers: []
{{ end }}

